#!/bin/bash
#sudo yum update -y
#BUCKET_NAME=$(curl http://metadata.google.internal/computeMetadata/v1/instance/attributes/bucket_name -H "Metadata-Flavor: Google")
DB_CONNECTION=$(curl http://metadata.google.internal/computeMetadata/v1/instance/attributes/db_connection -H "Metadata-Flavor: Google")

BITBUCKET_HOME=/var/atlassian/bitbucket
BITBUCKET_INSTALL=/opt/atlassian/bitbucket
JRE_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre/
#JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/

wget https://centos7.iuscommunity.org/ius-release.rpm
rpm -Uvh ius-release.rpm
yum install -y wget java-1.8.0-openjdk git2u postgresql gzip

#Create directoris BITBUCKET_HOME and BITBUCKET_INSTALL

mkdir -p "${BITBUCKET_HOME}"
mkdir -p "${BITBUCKET_INSTALL}"

wget https://www.atlassian.com/software/stash/downloads/binary/atlassian-bitbucket-5.12.0.tar.gz -O atlassian-bitbucket.tar.gz
tar -xvzf atlassian-bitbucket.tar.gz -C "${BITBUCKET_INSTALL}" --strip-components=1
rm atlassian-bitbucket.tar.gz
sed -i "s~BITBUCKET_HOME=~BITBUCKET_HOME=${BITBUCKET_HOME}~g" "${BITBUCKET_INSTALL}/bin/set-bitbucket-home.sh"
sed -i "s~JRE_HOME=~JRE_HOME=${JRE_HOME}~g" "${BITBUCKET_INSTALL}/bin/set-jre-home.sh"

chmod -R 700 "${BITBUCKET_HOME}"
chmod -R 700 "${BITBUCKET_INSTALL}"

echo "
[Unit]
Description=Atlassian Bitbucket Server Service
After=syslog.target network.target

[Service]
Type=forking
User=root
ExecStart=/opt/atlassian/bitbucket/bin/start-bitbucket.sh
ExecStop=/opt/atlassian/bitbucket/bin/stop-bitbucket.sh

[Install]
WantedBy=multi-user.target" > /etc/systemd/system/bitbucket.service

systemctl daemon-reload
sudo systemctl restart bitbucket

curl https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 --output /usr/local/bin/cloud_sql_proxy
chmod +x /usr/local/bin/cloud_sql_proxy
/usr/local/bin/cloud_sql_proxy -instances=${DB_CONNECTION}=tcp:5432 &
