#!/bin/bash

#sudo yum update -y
BUCKET_NAME=$(curl http://metadata.google.internal/computeMetadata/v1/instance/attributes/bucket_name -H "Metadata-Flavor: Google")
DB_CONNECTION=$(curl http://metadata.google.internal/computeMetadata/v1/instance/attributes/db_connection -H "Metadata-Flavor: Google")

#Install software
sudo yum install -y wget java-1.8.0-openjdk git2u postgresql
wget https://centos7.iuscommunity.org/ius-release.rpm
sudo rpm -Uvh ius-release.rpm

cd /opt/
sudo mkdir Atlassian && cd Atlassian
sudo wget https://www.atlassian.com/software/stash/downloads/binary/atlassian-bitbucket-5.12.0.tar.gz
sudo tar -xvzf atlassian-bitbucket-*.tar.gz
sudo rm atlassian-bitbucket-*.tar.gz
sudo ln -s atlassian-bitbucket-* atlassian-bitbucket

mkdir /opt/Bitbucket && cd /opt/Atlassian/atlassian-bitbucket/bin/

export BITBUCKET_HOME=/opt/Bitbucket
export JRE_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre/
export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/

# Copy bitbucket.service from bucket to instance
sudo gsutil cp gs://$BUCKET_NAME/bitbucket.service /etc/systemd/system/bitbucket.service

#Edit set-bitbucket-home.sh and set-jre-home.sh 
sudo sed -i '0,/BITBUCKET_HOME=/s//BITBUCKET_HOME=\/opt\/Bitbucket\//g' set-bitbucket-home.sh
sudo sed -i '0,/JRE_HOME=/s//JRE_HOME=\/usr\/lib\/jvm\/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64\/jre\//g' set-jre-home.sh 

sudo chmod 750 /opt/Bitbucket/
sudo ./start-bitbucket.sh 

# Start Bitbucket
systemctl start bitbucket

curl https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 --output /usr/local/bin/cloud_sql_proxy
chmod +x /usr/local/bin/cloud_sql_proxy
/usr/local/bin/cloud_sql_proxy -instances=${DB_CONNECTION}=tcp:5432 &
