#!/bin/bash
sudo yum update -y
sudo yum install -y wget java-1.8.0-openjdk
sudo wget https://centos7.iuscommunity.org/ius-release.rpm
sudo rpm -Uvh ius-release.rpm
sudo yum install -y git2u

cd /opt/
sudo mkdir Atlassian && cd Atlassian
sudo wget https://www.atlassian.com/software/stash/downloads/binary/atlassian-bitbucket-5.12.0.tar.gz
sudo tar -xvzf atlassian-bitbucket-*.tar.gz
sudo rm atlassian-bitbucket-*.tar.gz
sudo ln -s atlassian-bitbucket-* atlassian-bitbucket

sudo mkdir /opt/Bitbucket && cd /opt/Atlassian/atlassian-bitbucket/bin/
#відредагувати set-bitbucket-home.sh і вказати BITBUCKET_HOME


export BITBUCKET_HOME=/opt/Bitbucket

#echo $BITBUCKET_HOME
#export BITBUCKET_HOME=/opt/Bitbucket
#sudo nano set-bitbucket-home.sh 
sudo sed -i '0,/BITBUCKET_HOME=/s//BITBUCKET_HOME=\/opt\/Bitbucket\//g' set-bitbucket-home.sh
#echo $BITBUCKET_HOME 
export JRE_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre/
export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/
sudo sed -i '0,/JRE_HOME=/s//JRE_HOME=\/usr\/lib\/jvm\/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64\/jre\//g' set-jre-home.sh 
sudo chmod 750 /opt/Bitbucket/
sudo ./start-bitbucket.sh 
