#!/bin/bash
#sudo yum update -y
DB_CONNECTION=$(curl http://metadata.google.internal/computeMetadata/v1/instance/attributes/db_connection -H "Metadata-Flavor: Google")

yum install -y wget 
wget https://centos7.iuscommunity.org/ius-release.rpm
rpm -Uvh ius-release.rpm
yum install -y java-1.8.0-openjdk git2u postgresql gzip

BITBUCKET_HOME=/var/atlassian/bitbucket
BITBUCKET_INSTALL=/opt/atlassian/bitbucket
JRE_HOME=`alternatives --display java | awk '/'jre:'/{print $3}'`

#Create directory for BITBUCKET_HOME and BITBUCKET_INSTALL
mkdir -p "${BITBUCKET_HOME}"
mkdir -p "${BITBUCKET_INSTALL}"

wget https://www.atlassian.com/software/stash/downloads/binary/atlassian-bitbucket-5.12.0.tar.gz -O atlassian-bitbucket.tar.gz
tar -xvzf atlassian-bitbucket.tar.gz -C "${BITBUCKET_INSTALL}" --strip-components=1
rm atlassian-bitbucket.tar.gz

#Edit set-bitbucket-home.sh and set-jre-home.sh 
sed -i "s~BITBUCKET_HOME=~BITBUCKET_HOME=${BITBUCKET_HOME}~g" "${BITBUCKET_INSTALL}/bin/set-bitbucket-home.sh"
sed -i "s~JRE_HOME=~JRE_HOME=${JRE_HOME}~g" "${BITBUCKET_INSTALL}/bin/set-jre-home.sh"

adduser bitbucket
chown -R bitbucket "${BITBUCKET_HOME}"
chown -R bitbucket "${BITBUCKET_INSTALL}"
chmod -R 700 "${BITBUCKET_HOME}"
chmod -R 700 "${BITBUCKET_INSTALL}"

#Bitbucket.service daemon configuration 
echo "
[Unit]
Description=Atlassian Bitbucket Server Service
After=syslog.target network.target

[Service]
Type=forking
User=root
ExecStart=/opt/atlassian/bitbucket/bin/start-bitbucket.sh
ExecStop=/opt/atlassian/bitbucket/bin/stop-bitbucket.sh

[Install]
WantedBy=multi-user.target" > /etc/systemd/system/bitbucket.service

systemctl daemon-reload
systemctl restart bitbucket
systemctl enable bitbucket.service

#Update Cloud_sql_proxy and connectin to DB
curl https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 --output /usr/local/bin/cloud_sql_proxy
chmod +x /usr/local/bin/cloud_sql_proxy
/usr/local/bin/cloud_sql_proxy -instances=${DB_CONNECTION}=tcp:5432 &

#install elasticsearch
yum install java-1.8.0-openjdk
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.3.rpm
sha1sum elasticsearch-5.5.3.rpm
sudo rpm --install elasticsearch-5.5.3.rpm
sudo systemctl status elasticsearch.service
/usr/share/elasticsearch/bin/elasticsearch-plugin install -b https://packages.atlassian.com/maven/com/atlassian/elasticsearch/buckler-plugin/1.0.4/buckler-plugin-1.0.4-5.5.3.zip
###install nfs
#server
yum -y install nfs-utils
systemctl enable nfs-server.service
systemctl start nfs-server.service
mkdir /var/nfs
chown nfsnobody:nfsnobody /var/nfs-sahred
chmod 755 /var/nfs-shared
nano /etc/exports >> /var/nfs-shared    10.132.0.0/24(rw,sync,no_root_squash,no_all_squash)
exportfs -a

#client
yum install -y nfs-utils

